[package]
name = "cp7"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "*"
blake3 = "*"
enum_variant_type = "*"
notify = "*"
thiserror = "*"

[dependencies.clap]
version = "*"
features = ["derive"]
