[package]
name = "capi-compiler"
version = "0.1.0"
edition = "2021"

[dependencies.blake3]
version = "*"
features = ["serde"]

[dependencies.capi-runtime]
path = "../runtime"

[dependencies.serde]
version = "*"
features = ["derive"]
