[package]
name = "cp4"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
async-recursion = "*"
async-trait = "*"
crossterm = "*"
futures = "*"
thiserror = "*"

[dependencies.tokio]
version = "*"
features = ["full"]
