[workspace]
resolver = "2"
members = [
    "capi/capi",
    "capi/process",
    "capi/protocol",
    "tools/builder",
    "tools/daily",
]
default-members = ["tools/builder"]

[profile.dev]
opt-level = 3
