[workspace]
resolver = "2"
members = [
    "capi/build-game",
    "capi/compiler",
    "capi/debugger",
    "capi/ffi",
    "capi/game-engine",
    "capi/host",
    "capi/launcher",
    "capi/process",
    "capi/protocol",
    "capi/server",
    "capi/watch",

    "tools/builder",
    "tools/daily",
    "tools/website",
]
default-members = ["tools/builder"]

[profile.dev]
opt-level = 3
