[package]
name = "capi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
tempfile = "*"
warp = "*"

[dependencies.notify]
version = "*"

[dependencies.notify-debouncer-mini]
version = "*"

[dependencies.tokio]
version = "*"
features = ["full"]
