[workspace]
resolver = "2"
members = [
    "capi/compiler",
    "capi/debugger",
    "capi/ffi",
    "capi/process",
    "capi/protocol",
    "capi/runtime",
    "capi/server",
    "tools/builder",
    "tools/daily",
]
default-members = ["tools/builder"]

[profile.dev]
opt-level = 3
