[package]
name = "capi-builder"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "*"
notify-debouncer-mini = "*"
rocket = "*"
tempfile = "*"

[dependencies.tokio]
version = "*"
features = ["full"]
