[package]
name = "capi-game-engine"
edition = "2021"

[dependencies]
num_enum = "*"
serde = "*"
serde-big-array = "*"

[dependencies.capi-compiler]
path = "../compiler"

[dependencies.capi-runtime]
path = "../runtime"
