[package]
name = "capi-game-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
num_enum = "*"
serde = "*"
serde-big-array = "*"

[dependencies.capi-compiler]
path = "../compiler"

[dependencies.capi-process]
path = "../process"
