[workspace]
resolver = "2"
members = ["capi", "capi-debug", "capi-runtime"]
default-members = ["capi"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.capi]
opt-level = 3

[profile.dev.package.capi-runtime]
opt-level = 3
