[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"

[dependencies.notify]
version = "*"
default-features = false

[dependencies.tokio]
version = "*"
features = ["full"]
