[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
tempfile = "*"
tracing = "*"
tracing-subscriber = "*"
wasm-bindgen-cli-support = "*"

[dependencies.capi-watch]
path = "../../capi/watch"

[dependencies.tokio]
version = "*"
features = ["full"]
