[package]
name = "caterpillar"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-window-handle = "0.5.0"
sycamore = "0.8.2"
wasm-bindgen-futures = "0.4.33"

[dependencies.wgpu]
version = "0.14.2"
features = ["webgl"]
