[package]
name = "capi-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "*"

[dependencies.serde]
version = "*"
features = ["derive"]

[dependencies.udigest]
version = "*"
features = ["derive", "std"]
