[package]
name = "capi-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
ron = "*"

[dependencies.capi-ffi]
path = "../ffi"

[dependencies.capi-process]
path = "../process"

[dependencies.capi-protocol]
path = "../protocol"
