[package]
name = "capi-cli"
edition = "2021"

[dependencies]
anyhow = "*"
rand = "*"

[dependencies.capi-game-engine]
path = "../game-engine"

[dependencies.capi-build-game]
path = "../build-game"

[dependencies.tokio]
version = "*"
features = ["full"]
