[package]
name = "capi-tests"
version = "0.1.0"
edition = "2021"


[dev-dependencies]
anyhow = "*"

[dev-dependencies.capi-core]
path = "../capi-core"

[dev-dependencies.capi-desktop]
path = "../capi-desktop"
