[package]
name = "capi-protocol"
edition = "2021"

[dependencies]
ron = "*"

[dependencies.capi-compiler]
path = "../compiler"

[dependencies.capi-game-engine]
path = "../game-engine"

[dependencies.crosscut-runtime]
path = "../runtime"

[dependencies.serde]
version = "*"
features = ["derive"]
