[package]
name = "capi-vm"
version = "0.1.0"
edition = "2021"

[features]
std = ["thiserror"]


[dependencies.thiserror]
version = "*"
optional = true


[dev-dependencies]
anyhow = "*"

[dev-dependencies.capi-vm]
path = "."
features = ["std"]
