[package]
name = "capi-desktop"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "*"
crossbeam-channel = "*"
notify = "*"
notify-debouncer-mini = "*"
pixels = "*"
tracing = "*"
# `winit` 0.29 uses `raw-window-handle` 0.6, which `pixels` is still on 0.5.
# Once a version of `pixels` is available that supports 0.6, the version here
# can be replaced with `*` again.
winit = "<0.29.0"

[dependencies.capi-core]
path = "../capi-core"

[dependencies.clap]
version = "*"
features = ["derive"]

[dependencies.tracing-subscriber]
version = "*"
features = ["env-filter"]
