[package]
name = "capi-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"

[dependencies.capi-game-engine]
path = "../game-engine"

[dependencies.capi-watch]
path = "../watch"

[dependencies.tokio]
version = "*"
features = ["full"]
