[workspace]

[package]
name = "crosscut"
edition = "2021"

[dependencies]
anyhow = "*"
crossterm = "*"
pollster = "*"
pretty_assertions = "*"
udigest = "*"
wgpu = "*"
winit = "*"

[dependencies.blake3]
version = "*"
