[workspace]

[package]
name = "crosscut"
edition = "2021"

[dependencies]
anyhow = "*"
pollster = "*"
wgpu = "*"
winit = "*"

[dependencies.tokio]
version = "*"
features = ["rt", "rt-multi-thread", "sync"]
