[package]
name = "cp6"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
console_error_panic_hook = "*"
console_log = "*"
js-sys = "*"
log = "*"
sycamore = "*"
thiserror = "*"

[dependencies.web-sys]
version = "*"
features = ["KeyboardEvent"]
