[package]
name = "cp6"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
console_error_panic_hook = "*"
sycamore = "*"
thiserror = "*"

[dependencies.web-sys]
version = "*"
features = ["KeyboardEvent"]
